name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image 
      run:
        docker build -t bug-net-sync-service --pull .
    - name: Save the Docker image artifact
      uses: actions/upload-artifact@v2
      with: 
        name: docker-image
        path: bug-net-sync-service*

